# Generated by Django 4.0 on 2024-02-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='adminssion',
            new_name='admission',
        ),
    ]
