# Generated by Django 4.0 on 2024-02-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_eventcoordinator_categorycoordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycoordinator',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
