# Generated by Django 4.0 on 2024-03-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_latestnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
