# Generated by Django 4.0 on 2024-03-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='delete_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
