# Generated by Django 4.0 on 2024-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_newsitem_delete_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
